#

trigger:
  batch: true
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
- job: Linux
  dependsOn: []
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo apt-get install -y bison flex #g++-5
  - bash: cd AnimationEncoder; VERBOSE=1 make
  - task: ArchiveFiles@2
  - task: cURLUploader@2
    inputs:
      files: '**\*.zip'
      url: 'https://0x0.st'

- job: Test
  dependsOn: [Linux]
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: cd AnimationEncoder; make test

- job: Docs
  #dependsOn: [Test]
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: sudo apt-get install -y doxygen
  - bash: cd AnimationEncoder; make docs
  # deploy docs (on main/master)
# job deploy, depend on test, sha256, post to draft github release (on tag)
