#
# Deploy: Full success on main/master: docs to github pages, announce to irc?
# Release: Deploy plus tag: draft release notes?, package?
# Failure: not pr (unless marked RDY?): report
---
trigger:
  batch: true
  branches:
    include: ['*']
    exclude:
      - gh-pages
  tags:
    include: ['*']

pool:
  vmImage: 'ubuntu-16.04'
steps:
  - checkout: self  # Must be first in this file
    persistCredentials: true
  - script: sudo apt-get install bison flex
    displayName: Install requirements
  - bash: |
      cd $(Build.SourcesDirectory)/AnimationEncoder
      VERBOSE=1 CXXFLAGS="-Wall -Wextra -pedantic" make
      make help
    displayName: Build
  - bash: pwd; cd $(Build.SourcesDirectory)/AnimationEncoder; make test
    displayName: Test
    continueOnError: true

  # Tags trigger second build.
  - script: echo Deploy
    condition: and( succeeded(),
      eq( variables['System.PullRequest.IsFork'], 'False'),
      or( startsWith( variables['Build.sourceBranch'], 'refs/tag/'),
        eq( variables['Build.SourceBranch'], 'refs/heads/pipelines') ) )
    displayName: Deploy
  - template: templates/docs.yml
    parameters:
      makepath: AnimationEncoder
      target: docs
      path: doc/html/
      frontpage: README.md  # Add link to generated docs to this readme
  - template: templates/deploy.yml
    parameters:
      path: AnimationEncoder/encoder
      requirements: --version
      build_script: touch AnimationEncoder/encoder
  - template: templates/release.yml
    # condition: and( succeeded(),
    #  startsWith( variables['Build.sourceBranch'], 'refs/heads/'))  # heads>tag
    # displayName: Release
    parameters:
      connection: release
      path: AnimationEncoder/encoder
