#
---
trigger:
  batch: true
  branches:
    include: ['*']
    exclude:
      - gh-pages
  tags:
    include: ['*']

pool:
  vmImage: 'ubuntu-16.04'
steps:
  - checkout: self  # Must be first in this file
    persistCredentials: true
  - script: sudo apt-get install bison flex  # Cache this
    displayName: Install requirements
  - bash: cd $(Build.SourcesDirectory)/AnimationEncoder; VERBOSE=1 make
    displayName: Build
  - bash: cd $(Build.SourcesDirectory)/AnimationEncoder; make; make test || true
    displayName: Test
    continueOnError: true
  - template: templates/deploy.yml
    parameters:
      path: AnimationEncoder/encoder
      mainrepo: tobylane/CorsixTH-Graphics
  - template: templates/docs.yml
    parameters:
      makepath: AnimationEncoder
      target: docs
      path: doc/html/
      mainrepo: tobylane/CorsixTH-Graphics
